language: objective-c
xcode_project: Haitch.xcodeproj
xcode_scheme: HaitchTests
xcode_sdk: iphonesimulator
osx_image: xcode7.3

rvm:
  - 2.2.2

before_install: 
  - gem install slather --no-ri --no-rdoc

script:
#Make sure all tests pass
- xctool test -project Haitch.xcodeproj -scheme HaitchTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO

after_success: slather
