language: objective-c
xcode_project: Haitch.xcodeproj # path to your xcodeproj folder
xcode_scheme: HaitchTests
osx_image: xcode7.3

script:
- xcodebuild clean build test -project Haitch.xcodeproj -scheme HaitchTests
