language: objective-c
xcode_project: Haitch.xcodeproj
xcode_scheme: HaitchTests
osx_image: xcode7.3

before_install: rvm use $RVM_RUBY_VERSION
install: bundle install --without=documentation --path ../travis_bundle_dir
after_success: slather

script:
#Make sure all tests pass
- xctool test -project Haitch.xcodeproj -scheme HaitchTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
