language: objective-c
xcode_project: Haitch.xcodeproj
xcode_scheme: HaitchTests
osx_image: xcode7.3

script:
# Insure it builds
- xctool clean build -project Haitch.xcodeproj -scheme "Haitch iOS" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
#Make sure all tests pass
- xctool test -project Haitch.xcodeproj -scheme HaitchTests -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
